version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      MEMORY: "8G"
      EULA: "TRUE"
      VERSION: "1.19.2"
      TYPE: "SPIGOT"
      SPIGOT_RESOURCES: "64348,9089"
      MOTD: "Ur welcome Sarita :)"
    tty: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./data/data:/data
      - ./data/mods:/mods
